### ISSUE TITLE
Make Stored Procedure Files

### ISSUE THREAD

**Issue by mjllewelyn** [mjllewelyn/CIS560-Project#2]
We are making the queries into stored procedures which the application will call

**Comment by mikexc1026** [comment]
Initial List of queries:

Report Queries:
- [x] Race summary
- Number of participants
- Average pace of all runners collectively
- Winning time
- [ ] Fastest time for each runner on a specific team
- [x] Team placing for a race
- Based on that teams average runner placing in that race
- [x] Runner Summary based on all runs by that runner
- Average run distance
- Average run time
- Average run pace

Other Queries:
- [ ] Return all user attributes based on email and password if exists
- [ ] List of runners on a team
- [ ] List of races a team has run
- [ ] List of races based on date
- [ ] List of runs for a runner
- [ ] List of races a runner has run
- [ ] List a users email, first and last name, and starting year
- [ ] List all runs for a runner at a certain location
- [ ] List average time for all races a runner has run by year

Feel free to comment suggested changes to this list. It will probably need to be edited as we start working on it.

**Comment by mikexc1026** [comment]
New list(good luck):
- [x] Get race participant (RaceParticipantId)
- [x] Fetch runners for race (RaceId)
- [x] Fetch races for runner (RunnerId)
- [x] Get Coach (CoachId)
- [x] Get Location (LocationId)
- [ ] Get Team Records (TeamId)
- [x] Update Race Participant Time (RaceParticipantId, Time)
- [x] Create Race Participant (RaceId, RunnerId, Time, AverageHeartRate)
- [x] Retrieve Races
- [x] Get Race (RaceId)
- [x] Create Race (CreatorId, LocationId, DateTime, Distance, IsArchived)
- [x] Archive Race (RaceId)
- [x] Retrieve Runners
- [x] Get Runner (RunnerId) 
- [x] Get Team Runners (TeamId)
- [x] Get Runners No Team 
- [x] Get Team (TeamId)
- [x] Fetch Coach Teams (CoachId)
- [x] Get Teams for Race (RaceId)
- [x] Create Team (Name, CoachId, CreatedOn, UpdatedOn, StartYear, EndYear)
- [x] Retire Team (TeamId)
- [x] Get Training Run (TrainingRunId)
- [x] Fetch Training Runs (RunnerId)
- [x] Create Training Run (RunnerId, Date, Distance, Time, AverageHeartRate, IsArchived)
- [x] Get User (Email)
- [x] Validate User (Email, Password)
- [x] Retire User (UserId)
- [x] Get Coach's Runners' User (CoachId)
- [x] Get Locations
       - Returns all locations 
- [x] Get Dates for Location (LocationId)
       - Returns the dates of all future races at a given location
- [x] FetchRacesForTeam(TeamId)
       - Returns races a team has run
